### ISSUE TITLE
Trouble DLing 1.4

### ISSUE THREAD

**Issue by PDubulous** [Esri/vitruvio#129]
I get an unexpected error on v 1.4 when I try to extract it.  I DL'd 1.3 and several of the other packages with no issues, and I turned my AV off.  Seems like it must be something specific in 1.4.

![image](https://github.com/Esri/vitruvio/assets/5695994/053310ff-6a5d-47f3-a951-79fc5cac50be)

This is not the only file that throws the error.  Let me know if you need more info.

Thanks!

EDIT: I was able to DL the source and compile it with the prompt.  No luck on the packaged file though.

**Comment by bneukom** [comment]
Hi,

Thanks for letting us now! It seems the file could only be unzipped with 7zip. I updated the zip file and it should work with Windows unzip as well now.

Let me know if it works for you.

**Comment by PDubulous** [comment]
Worked like a champ.  Thanks!
