### ISSUE TITLE
Unreal Engine 5.4

### ISSUE THREAD

**Issue by omegartlx** [Esri/vitruvio#145]
I know it just came out but i really need motion matching and this plugin at the same time.

**Comment by deedox** [comment]
> I know it just came out but i really need motion matching and this plugin at the same time.

Me too. Would be nice to have it soon in UE 5.4

**Comment by bneukom** [comment]
The release is now out: https://github.com/Esri/vitruvio/releases/tag/v2.1

Let us now if you encounter any issues.
