### ISSUE TITLE
Can't find VitruvioActor, errors in demos

### ISSUE THREAD

**Issue by Psijic** [Esri/vitruvio#151]
I installed Vitruvio as a Linux UE 5.4.2 plugin but can't load demo projects without errors. Also I can't use Vitruvio in an empty project -can't find VitruvioActor  

Errors in demo projects like Paris:
`CreateExport: Failed to load Outer for resource 'Root': VitruvioActor /Game/Boston.Boston:PersistentLevel.VitruvioActor_1
`

Error in BP compilation
```
Could not find a variable named "VitruvioComponent" in '/Vitruvio/Demo/BP_ReportDisplay.BP_ReportDisplay'.
Make sure '/Vitruvio/Demo/BP_ReportDisplay.BP_ReportDisplay' has been compiled for  Get VitruvioComponent
In use pin  Target  no longer exists on node  Get . Please refresh node or break links to remove pin.
In use pin  Report  no longer exists on node  Break <unknown struct> . Please refresh node or break links to remove pin.
In use pin  Name  no longer exists on node  Break <unknown struct> . Please refresh node or break links to remove pin.
In use pin  Value  no longer exists on node  Break <unknown struct> . Please refresh node or break links to remove pin.
No Struct in  Break <unknown struct>
In use pin  Target  no longer exists on node  Get Reports . Please refresh node or break links to remove pin.
```
![Screenshot_20240715_203658](https://github.com/user-attachments/assets/3dddd2cb-2d01-4f1b-84bf-ab5dc925ed45)

**Comment by bneukom** [comment]
Hi @Psijic

Unfortunately Vitruvio is currently only supported on Windows.

**Comment by Psijic** [comment]
What is needed to support Linux? The plugin looks installed already.

**Comment by bneukom** [comment]
There is still some implementation needed to fully support Linux. But I will have a look if it is doable in a reasonable amount of time :) I will let you know about the outcome here.

**Comment by Psijic** [comment]
> There is still some implementation needed to fully support Linux. But I will have a look if it is doable in a reasonable amount of time :) I will let you know about the outcome here.

Is there a specific month to wait for? :)
