### ISSUE TITLE
Vitruvio Actor Attribute Issue

### ISSUE THREAD

**Issue by jpatton-hlplanning** [Esri/vitruvio#153]
**Description:** I'm experiencing an issue with Vitruvio 1.4 in Unreal Engine 5.2 when working with static mesh actors (specifically planes) and Vitruvio components.

**Details:** When I add a Vitruvio component to a static mesh actor and assign an RPK file, the attributes of the file are correctly exposed, allowing me to change and adjust them. The building is generated as expected during the initial environment start, and everything works as intended.

However, when I convert the static mesh actor to a Vitruvio actor (to enable runtime regeneration of buildings), I assign the same RPK file, but the attributes are not exposed. This behavior seems inconsistent, as the attributes are visible when using the Vitruvio component but not when using the Vitruvio actor.

I've attached screenshots for reference. In the first screenshot, you can see the attributes exposed correctly for the Vitruvio component. In the second screenshot, the Vitruvio actor with the same RPK assigned does not display any attributes.
 
**Expected Behavior:** The attributes should be exposed in both cases—whether I use a Vitruvio component or a Vitruvio actor—so that I can regenerate buildings during runtime.

**Attributes Exposed on StaticMeshActor with VitruvioComponent**
![vit2](https://github.com/user-attachments/assets/a1808a7f-0eaa-4023-a0f7-73dcfeed26db)

**Attributes not showing in actual Vitruvio Actor**
![vit1](https://github.com/user-attachments/assets/0acc7bed-2f8f-48aa-9ae7-67302addafec)

**Comment by bneukom** [comment]
Hi @jpatton-hlplanning 

Thank your for reporting this issue! 

I just tried to reproduce it with the latest Vitruvio version (2.1) for Unreal 5.4 and it seems to have been fixed. Would it be possible for you to upgrade to Unreal 5.4?

I'm trying to find a fix for Vitruvio 1.4 but it might take a bit more time.

**Comment by bneukom** [comment]
I backported the latest Vitruvio version (2.1) for Unreal 5.2 which should also solve the issue. Could you try this build and verify that everything works? 

https://esriis-my.sharepoint.com/:u:/g/personal/benj9250_esri_com/EYdILce5g7RLtRxYJGNn0ZIByQ_cxGxIwsd0qw7W44IBQg?e=RhIho2

In case it doesn't work, I would need your RPK to investigate further. 

Thank you.

**Comment by jpatton-hlplanning** [comment]
Everything is now working as expected.
Thank you for the timely response!
