### ISSUE TITLE
Vitruvio Generation Missing Collision

### ISSUE THREAD

**Issue by jpatton-hlplanning** [Esri/vitruvio#154]
### Collision Issue with Vitruvio Actors in Packaged Builds - UE 5.4 (Vitruvio 2.1)

**Summary:**
After upgrading to Unreal Engine 5.4 and Vitruvio 2.1, I encountered an issue with collision on Vitruvio-generated actors.
Hit tests work correctly in the editor, but collisions fail in the packaged build.

**Steps to Reproduce:**
1. Generate a Vitruvio actor in the editor using Unreal Engine 5.4 and Vitruvio 2.1.
2. Perform hit tests on the actor to modify the model during runtime.
3. Package the project.
4. In the packaged version, hit tests no longer work, and collision seems to be lost.

**Expected Behavior:**
Hit tests and collision should work in both the editor and the packaged build.

**Actual Behavior:**
Collision works in the editor, but after packaging, the generated models lose their collision, and hit tests fail to register.

**Additional Information:**
I confirmed the issue is with the generated model by adding a cube inside the parent actor, both the cube and the original footprint have collision, confirming the issue is isolated to the Vitruvio-generated model.
In the Vitruvio settings, is there supposed to be a checkbox labeled "Generate Collision Mesh"? I see the checkbox in the github docs but not my environment.

Thanks

**Hit Test Packaged Project**
![hitBad](https://github.com/user-attachments/assets/afb7fea8-4208-4784-820f-10331a45679d)

**Hit Test Editor Window**
![hitGood](https://github.com/user-attachments/assets/14c13098-373f-4473-a8f5-e8b069df998c)

**Missing "Generate Collision Mesh" checkbox?**
![hitSettings](https://github.com/user-attachments/assets/a1169276-4087-46fe-a18b-63b2617506a1)

**Comment by bneukom** [comment]
Hi @jpatton-hlplanning 

Thank you for reporting the issue! I created a fix [here](https://esriis-my.sharepoint.com/:u:/g/personal/benj9250_esri_com/EcFZ995fSPdOgQReyh1eIiIBuFKGlQTNgRl7EMuOsi9jKA?e=MYljKJ).

Could you test this version and let me know if everything works as expected? If it works I will create an official bug fix release.

**Comment by bneukom** [comment]
Fixed the bug and published a new release https://github.com/Esri/vitruvio/releases/tag/v2.1.1
