### ISSUE TITLE
Add geometry cooking support

### ISSUE THREAD

**Issue by bneukom** [Esri/vitruvio#29]
Currently it is not possible to save generated geometry. For some applications it might make sense to "cook" (save the generated geometry) the VitruvioActors so that they don't have to be procedurally generated anymore (eg before relasing a packaged build where no interaction with the VitruvioActor is necssary). This could save performance in such cases and also allow for proper collision mesh setup.

Tasks:
- Add additional context menu entry to "Cook Vitruvio Actors"
- This should generate static mesh for the generated geometry as well as instances
- Also consider instance and material reusing
- Add option to also immediatly replace the procedural VitruvioActors with the cooked geometry
  - Maybe it would also make sense to support the reverse (eg convert the cooked geometry back to a procedural VitruvioActor). This would require to store the attributes which were used for generation to be stored somehow

**Comment by romainjanil** [comment]
interesting, thinking vitrivio generation result as full ue actors would open a lot of possibilities, particularly for instances and shareable material instances. On the subject of  reusing material, I didn't test it so may be it already works, it would be great if direct material shader redirection like with datasmith could be supported, if coded properly in the RPK cga (so static generated meshes would use some consolidated material instances directly, if they exists).

**Comment by bneukom** [comment]
Hi Romain!

> On the subject of reusing material, I didn't test it so may be it already works, it would be great if direct material shader redirection like with datasmith could be supported, if coded properly in the RPK cga (so static generated meshes would use some consolidated material instances directly, if they exists).

This actually already works. You can set the CGA material.shader to a material path for Unreal (eg. `set(material.shader, "/Game/Materials/M_Grass")`). If a mterial at the specified path exists (for this example in the Content/Materials/M_Grass) it will be used as the parent material of the material for the generated mesh. This even allows you to use material parameters from CityEngine in your custom parent Material (for example the diffuseColor attribute).

**Comment by bneukom** [comment]
Added with https://github.com/Esri/vitruvio/pull/49 https://github.com/Esri/vitruvio/pull/51 https://github.com/Esri/vitruvio/pull/57. Closing this now.
