### ISSUE TITLE
Unclear how to spawn city from correctly exported RPK

### ISSUE THREAD

**Issue by fpibbs** [Esri/vitruvio#35]
Hi,
I can import RPK file, but it's not procedurally generating the city.
RPK exported with CGA from CityEngine 2019.
I'm on the Paris Base project.

Can be some clarifications about the procedure?

**Comment by bneukom** [comment]
Hi!

Can you try the steps described here https://github.com/Esri/vitruvio/blob/master/doc/usage.md#advanced and let me know if that works for you?

**Comment by bneukom** [comment]
I'll assume the problem is solved. Otherwise please report your issue on [GeoNet ](https://community.esri.com/t5/arcgis-cityengine-plugin/bd-p/arcgis-cityengine-plugin-questions) again.
