### ISSUE TITLE
Can you add a runtime example? What is the API to generate from code instead of the editor?

### ISSUE THREAD

**Issue by lukemadera** [Esri/vitruvio#36]
The description of Vitruvio says "..for the generation of procedural buildings in the Unreal Editor or at runtime". I've seen examples of how to export from CityEngine to the Unreal Editor using Datasmith, but I haven't been able to find any examples of how to generate a city at runtime (outside the editor, after the game has been built). I'm assuming this is what is meant by "runtime"? I've seen the Python & C++ plugins so I'm assuming it has something to do with that? The jupyter notebooks with pyprt seem close - import the rule package and then generate the 3D building / tree / city.
https://github.com/Esri/pyprt-examples/blob/master/ex7_building_modeling_optimization.ipynb
This example does it in the web:
https://www.esri.com/arcgis-blog/products/city-engine/3d-gis/converting-3d-geometry-formats-made-simple-using-pyprt/
But I haven't seen an example of doing it within an Unreal game.

Specifically, I want to be able to do everything in code - so have a rule package file and then use that plus user input in the game to generate a tree or building or entire city dynamically (rather than pre-built). Is this possible and if so, is there a tutorial for the code to do this? Thanks!

**Comment by bneukom** [comment]
Hi!

> Specifically, I want to be able to do everything in code - so have a rule package file and then use that plus user input in the game to generate a tree or building or entire city dynamically (rather than pre-built). Is this possible and if so, is there a tutorial for the code to do this?

There is no tutorial for that yet but I will try to get something like this done for a future release. I did some testing though and can give you some hints to make it work. Note that this API will most likely change in the future to make it simpler. 

For now the code should look something like this:

```c++
// Requires a rule package with the name "nyc2259" in the Content folder. Change this path to your custom rule package path
URulePackage* RulePackage = LoadObject<URulePackage>(NULL, TEXT("/Game/nyc2259.nyc2259"), NULL, LOAD_None, NULL);

// Spawn the Vitruvio Actor
AVitruvioActor* VitruvioActor = GetWorld()->SpawnActor<AVitruvioActor>();

// Attach a SplineComponent which is used as the initial shape
USplineComponent* Component = NewObject<USplineComponent>(VitruvioActor, TEXT("InitialShapeSpline"));
Component->Mobility = EComponentMobility::Movable;
VitruvioActor->AddInstanceComponent(Component);
Component->AttachToComponent(VitruvioActor->GetRootComponent(), FAttachmentTransformRules::KeepRelativeTransform);
Component->OnComponentCreated();
Component->RegisterComponent();

// Create initial shape geometry
Component->ClearSplinePoints();
Component->SetClosedLoop(true);

TArray<FVector> Vertices = { FVector(0, 0, 0), FVector(2000, 0, 0), FVector(2000, 2000, 0), FVector(0, 2000, 0) };
int32 PointIndex = 0;
for (const FVector& Position : Vertices)
{
    Component->AddSplineLocalPoint(Position);
    Component->SetSplinePointType(PointIndex++, ESplinePointType::Linear, true);
}

UVitruvioComponent* VitruvioComponent = VitruvioActor->VitruvioComponent;
VitruvioComponent->SetRpk(RulePackage);

// Initialize the actor and generate the model
VitruvioActor->Initialize();
VitruvioComponent->Generate();
```

I added this to the `BeginPlay` function of an Actor and added this Actor to the level. This code basically spawns a `VitruvioActor`, sets up the initial shape geometry (as a quad, but can be changed to any shape you like) and then generates the building. Remember to add "Vitruvio" to your "PublicDependencyModuleNames" in the .Build.cs file.

Let me know if that helps or you need more information.

**Comment by lukemadera** [comment]
Thanks so much for the prompt and detailed reply @bneukom ! I'll try it out. One related question - I've noticed Vitruvio states it is Windows only? I have a Mac (no Windows at the moment) - do I need to get a Windows to be able to use this and is there any reason it is Windows only? I'm assuming the end result (game) will run on all the platforms Unreal runs on, which includes far more than just Windows, so maybe it will work? And similarly any reason there's an Unreal plugin but not for Unity?
I've been using Unity for the past year and am new to Unreal and architecture tools so am surveying options and thus far CityEngine seems to be the only runtime option I've seen to procedurally generate environments and cities (Houdini seems cool but doesn't seem to have a runtime option). If this is the only / best option I'm willing to invest in / switch to Unreal, CityEngine and Windows, but obviously want to make sure it can do what we need beforehand!

**Comment by lukemadera** [comment]
Following up with some more background @bneukom - our goal is to give the end user the ability to procedurally generate and we want to support as many platforms as possible (most will not have high end gaming systems). Web and phone may be tricky and require lower fidelity but either way I'm thinking maybe we'll want to do the generation in the cloud / on our servers (which we can control the hardware specs for) then stream the post generated data (actors & attributes) to Unreal running on the end user's device. In that case, that would mean we'd actually need the Python or C++ CityEngine SDKs rather than Vitruvio, correct?
https://esri.github.io/cityengine/pyprt

Also, is CityEngine generation deterministic? E.g. will it generate the same building each time? I'd assume no, since the whole point is to get unique, dynamic generations. But if we wanted to do multiplayer, we'd need all users to see the SAME dynamically generated actors / objects / content, so we'd have to do it server side then pass / stream the final content to all end users. This is how I did it for the Unity multiplayer game I built; I'd store the GameObject attributes in a database and all users in the same game would read those and then have the scene dynamically re-built in Unity from that.

So the direct question here is: for our use case do you think server side CityEngine is best? Or would you still recommend Vitruvio to procedurally generate on the end user's machine? Even if we did generate on the end user machine though, for multiplayer we'd either need a way to generate the exact same copy for all users in the same game OR a way to share the final generated result across all users.
In which case, we'd want to get the OUTPUT of the last line of code you shared, `VitruvioComponent->Generate();` and stream that down to all users. Speaking of - what does that output look like / are there any examples? Just a bunch of Unreal actors and attributes?
Thank you so much!!

**Comment by bneukom** [comment]
Hi again. Sorry for the late reply! I'm trying to answer some of the questions :) For further followup questions please post them on [here](https://community.esri.com/t5/arcgis-cityengine-plugin/bd-p/arcgis-cityengine-plugin-questions).

> I've noticed Vitruvio states it is Windows only? I have a Mac (no Windows at the moment) - do I need to get a Windows to be able to use this and is there any reason it is Windows only?

Yes for now we only support Windows (for runtime generation!) The problem is that the underlying CityEngine SDK which is used for the procedural generation only supports Windows and rhel. But if you do not need runtime procedural generation (only in the Unreal Editor) you could still develop your game on Windows and then "cook" your generated buildings into normal Static Meshes and disable the Plugin at runtime.

> Also, is CityEngine generation deterministic? E.g. will it generate the same building each time?

Yes it is. There is a seed number which is used to control all random aspects of the procedural generation. If you generate the same building with the same seed it will always result in the same generated geometry.

> Web and phone may be tricky and require lower fidelity but either way I'm thinking maybe we'll want to do the generation in the cloud / on our servers (which we can control the hardware specs for) then stream the post generated data (actors & attributes) to Unreal running on the end user's device.

Not sure I can answer that one because it probably also touches "legal" aspects of the CityEngine SDK. Probably again best to ask it [here](https://community.esri.com/t5/arcgis-cityengine/ct-p/arcgis-cityengine).

**Comment by lukemadera** [comment]
Thanks for the follow up! I may be more confused now than before though and I'm not clear what the "legal" aspects you referred to were. We definitely need runtime generation; that's the key point and what looked really awesome about CityEngine! I'll try other options for now then and if I need to circle back will try looking at those forums you linked to. Thanks.
