### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by nisargpatel220303** [Esri/vitruvio#40]
I am not able to see vitruvio component drop-down list, everything else ios coming except this drop-down folder where it has all the attributes

**Comment by bneukom** [comment]
Do you mean the list of attributes is not showing? Have you already assigned a Rule Package? And does your rule file expose any attributes? 

If it does not work, could you try:

- Open the example map in the Vitruvio Plugin (Content/Demo/Vitruvio_Demo) and check if the attributes show up on the VitruvioActor.
- Or download an example from [the examples](https://esri.github.io/cityengine/vitruvio#examples) and check if the attributes show up on the VitruvioActor.

**Comment by nisargpatel220303** [comment]
Ok I will give it a try Sent from Mail for Windows 10 From: Benjamin NeukomSent: Monday, March 22, 2021 7:52 PMTo: Esri/vitruvioCc: nisargpatel220303; AuthorSubject: Re: [Esri/vitruvio] issue (#40) Do you mean the list of attributes is not showing? Have you already assigned a Rule Package? And does your rule file expose any attributes?If it does not work, could you try:Open the example map in the Vitruvio Plugin (Content/Demo/Vitruvio_Demo) and check if the attributes show up on the VitruvioActor.Or download an example from the examples and check if the attributes show up on the VitruvioActor.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bneukom** [comment]
I assume this has been solved. Otherwise please feel free to ask again on https://community.esri.com/t5/arcgis-cityengine-plugin/bd-p/arcgis-cityengine-plugin-questions
