### ISSUE TITLE
UE5 Compatibility

### ISSUE THREAD

**Issue by Liquid-Martin** [Esri/vitruvio#44]
Can we expect a release of of Vitruvio that supports Unreal Engine 5?

Echoing a question that was put in UE Marketplace [here](https://www.unrealengine.com/marketplace/en-US/product/vitruvio-cityengine-plugin/questions).

Thanks!

**Comment by bneukom** [comment]
Hi @Liquid-Martin!

Yes we are planning on upgrading to UE5 (and hopefully make use of some of the new features) once it is officially released.

**Comment by bneukom** [comment]
This has been added with https://github.com/Esri/vitruvio/pull/75
