### ISSUE TITLE
Support concave initial shapes

### ISSUE THREAD

**Issue by hasretg** [Esri/vitruvio#46]
It can happen that the generated building is upside down, when applying a RPK to a concave shape and changing from static mesh to splines for further processing. 

Tasks:
- Compute the polygon orientation using a more sophisticated algorithm (There might already be something implemented in Unreal like for example in `PolygonTriangulation::ComputePolygonPlane`)
- Use the orientation to properly order the vertices of the polygon

**Comment by bneukom** [comment]
Fixed with #64.
